### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jonjomckay** [ChazSII/Simple-AES256#1]
Hello, is this code released under any kind of open source license? I realise in your `README.md` that the license status is "TODO: Write license" but we'd like to use this in another open-source project so it would be great to know!

**Comment by ChazSII** [comment]
Sorry for the delay, I have added a license file and updated the License section of the readme. Hope this can help you out with your project. File any issues you find with it here, it was pretty much a first run helper class, so it could be buggy.
